In [1]:
import numpy as np
import pandas as pd

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchmetrics import Accuracy

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error 

from kan import *
import warnings
import sys
sys.path.append('../utils')
from treasury_base import *

warnings.filterwarnings("ignore")

torch.set_default_dtype(torch.float64)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


In [257]:
def direct_pred_retrieval():
    data = treasury_data_retrieval('us_treasury_rates_large.csv')
    data = data.set_index('Date')
    targets = data.columns
    window_list = [1, 5]
    lag_list = [1]
    shift_list = [_ for _ in range(20)]

    for shift in shift_list:
        for col in targets:
            data[f'{col}_+_{shift}'] = data[col].shift(-shift)

    for lag in lag_list:
        for window in window_list:
            for col in targets:
                data[f'{col}_-_{lag}_window_{window}'] = data[col].shift(1).rolling(window).mean()
    return data, targets

def train_mse():
    predictions = model(dataset['train_input'])  # Model predictions
    mse = F.mse_loss(predictions, dataset['train_label'], reduction='mean')  # Compute MSE
    return mse ** 0.5  # Return scalar MSE value

def test_mse():
    predictions = model(dataset['test_input']) # Model predictions
    mse = F.mse_loss(predictions, dataset['test_label'], reduction='mean')  # Compute MSE
    return mse ** 0.5

In [258]:
data, ori_col = direct_pred_retrieval()
all_cols = data.columns
data.tail()

1 Mo  2 Mo  3 Mo  6 Mo  1 Yr  2 Yr  3 Yr  5 Yr  7 Yr  10 Yr  ...  \
Date                                                                     ...   
2024-12-02  4.75  4.63  4.51  4.43  4.30  4.17  4.11  4.08  4.13   4.19  ...   
2024-12-03  4.66  4.56  4.49  4.40  4.27  4.17  4.13  4.11  4.17   4.23  ...   
2024-12-04  4.65  4.54  4.47  4.38  4.23  4.13  4.09  4.07  4.13   4.19  ...   
2024-12-05  4.59  4.53  4.46  4.38  4.23  4.15  4.10  4.07  4.12   4.17  ...   
2024-12-06  4.57  4.50  4.42  4.34  4.19  4.10  4.05  4.03  4.09   4.15  ...   

            3 Mo_-_1_window_5  6 Mo_-_1_window_5  1 Yr_-_1_window_5  \
Date                                                                  
2024-12-02              4.608              4.444              4.360   
2024-12-03              4.584              4.438              4.336   
2024-12-04              4.558              4.426              4.316   
2024-12-05              4.530              4.412              4.288   
2024-12-06              4.502              4.402              4.266   

            2 Yr_-_1_window_5  3 Yr_-_1_window_5  5 Yr_-_1_window_5  \
Date                                                                  
2024-12-02              4.222              4.202              4.160   
2024-12-03              4.182              4.160              4.116   
2024-12-04              4.174              4.144              4.104   
2024-12-05              4.158              4.120              4.084   
2024-12-06              4.150              4.106              4.076   

            7 Yr_-_1_window_5  10 Yr_-_1_window_5  20 Yr_-_1_window_5  \
Date                                                                    
2024-12-02              4.214               4.282               4.546   
2024-12-03              4.170               4.238               4.504   
2024-12-04              4.162               4.230               4.498   
2024-12-05              4.140               4.208               4.476   
2024-12-06              4.130               4.192               4.458   

            30 Yr_-_1_window_5  
Date                            
2024-12-02               4.466  
2024-12-03               4.418  
2024-12-04               4.408  
2024-12-05               4.382  
2024-12-06               4.360  

[5 rows x 276 columns]

In [272]:
test_size = 5
df_train, df_test = data[-test_size-500:-test_size], data[-test_size:]
len_train = len(df_train)
pred = list()

for h in range(0, 5):
    if h == 0:
        target_col = ori_col
    else:
        target_col = [f'{element}_+_{h}' for element in ori_col]
    
    feature_col = [element for element in all_cols if 'window' in element]

    df_train_modified = df_train[:(len_train-h)]
    df_test_modified = df_test.iloc[[0]]
    print(len(df_train_modified))

    X_train, y_train = df_train_modified[feature_col], df_train_modified[target_col]
    X_test, y_test = df_test_modified[feature_col], df_test.iloc[h][ori_col]

    n_inputs = X_train.shape[1]
    n_outputs = y_train.shape[1]

    dataset = dict()
    dtype = torch.get_default_dtype()
    dataset['train_input'] = torch.from_numpy(X_train.values).type(dtype).to(device)
    dataset['train_label'] = torch.from_numpy(y_train.values).type(dtype).to(device)
    dataset['test_input'] = torch.from_numpy(X_test.values).type(dtype).to(device)
    dataset['test_label'] = torch.from_numpy(y_test.values).type(dtype).to(device)

    # Initialize the model
    model = KAN(width=[n_inputs, 48, 64, n_outputs], grid=3, k=2, seed=42, device=device)

    # Train the model and compute metrics
    results = model.fit(dataset, opt="Adam", lamb=0.0001, lr=0.001, steps=500, metrics=(train_mse, test_mse))

    # loss_fn = loss_fn_eval = lambda x, y: torch.mean((x - y) ** 2)
    # p = 
    # train_loss = loss_fn(p, dataset['train_label'])
    # print(train_loss)
    # torch.sqrt(train_loss).cpu().detach().numpy()


    pred.append(model.forward(dataset['test_input']).cpu().detach().numpy().flatten())
    # print(n_inputs, n_outputs)

# df_train_modified
# df_test_modified
# y_train
# X_test
# model(dataset['test_input'])

500
checkpoint directory created: ./model
saving model version 0.0


description:   0%|                                                          | 0/500 [00:00<?, ?it/s]

| train_loss: 8.25e-02 | test_loss: 4.31e-01 | reg: 2.30e+02 | : 100%|█| 500/500 [01:56<00:00,  4.28


saving model version 0.1
499
checkpoint directory created: ./model
saving model version 0.0


| train_loss: 9.76e-02 | test_loss: 3.55e-01 | reg: 2.30e+02 | : 100%|█| 500/500 [01:56<00:00,  4.28


saving model version 0.1
498
checkpoint directory created: ./model
saving model version 0.0


| train_loss: 1.08e-01 | test_loss: 3.44e-01 | reg: 2.29e+02 | : 100%|█| 500/500 [01:55<00:00,  4.31


saving model version 0.1
497
checkpoint directory created: ./model
saving model version 0.0


| train_loss: 1.18e-01 | test_loss: 3.00e-01 | reg: 2.28e+02 | : 100%|█| 500/500 [01:53<00:00,  4.40


saving model version 0.1
496
checkpoint directory created: ./model
saving model version 0.0


| train_loss: 1.26e-01 | test_loss: 2.86e-01 | reg: 2.27e+02 | : 100%|█| 500/500 [01:54<00:00,  4.37


saving model version 0.1


In [275]:
real = df_test[ori_col].values
mean_squared_error(real, pred, squared=False)

np.float64(0.07875325190440506)

In [276]:
naive = [df_train[ori_col].iloc[-1].values] * test_size
mean_squared_error(real, naive, squared=False)

np.float64(0.05929291173832928)

In [273]:
pred

[array([4.69544278, 4.71069144, 4.67840542, 4.51235291, 4.30980869,
        4.19021114, 4.14172282, 4.09998143, 4.14696275, 4.20673658,
        4.48985022, 4.38152552]),
 array([4.69531768, 4.71269998, 4.66939001, 4.50844905, 4.30441138,
        4.19299315, 4.14387141, 4.10690895, 4.14840096, 4.20959317,
        4.49030159, 4.38511455]),
 array([4.69487669, 4.71299156, 4.66394307, 4.51053315, 4.30360925,
        4.19762096, 4.15576811, 4.11671228, 4.1499071 , 4.20787191,
        4.48908837, 4.38155671]),
 array([4.68672729, 4.71107045, 4.63740661, 4.51232615, 4.31126324,
        4.19620497, 4.14887123, 4.12820848, 4.15349686, 4.19909076,
        4.48681011, 4.36382418]),
 array([4.6900663 , 4.71190968, 4.63567314, 4.51088291, 4.31465183,
        4.19764621, 4.1508259 , 4.13174239, 4.14905532, 4.19600166,
        4.48861687, 4.36397623])]

In [277]:
real

array([[4.75, 4.63, 4.51, 4.43, 4.3 , 4.17, 4.11, 4.08, 4.13, 4.19, 4.46,
        4.36],
       [4.66, 4.56, 4.49, 4.4 , 4.27, 4.17, 4.13, 4.11, 4.17, 4.23, 4.5 ,
        4.4 ],
       [4.65, 4.54, 4.47, 4.38, 4.23, 4.13, 4.09, 4.07, 4.13, 4.19, 4.45,
        4.35],
       [4.59, 4.53, 4.46, 4.38, 4.23, 4.15, 4.1 , 4.07, 4.12, 4.17, 4.43,
        4.33],
       [4.57, 4.5 , 4.42, 4.34, 4.19, 4.1 , 4.05, 4.03, 4.09, 4.15, 4.42,
        4.34]])

In [278]:
naive

[array([4.76, 4.69, 4.58, 4.42, 4.3 , 4.13, 4.1 , 4.05, 4.1 , 4.18, 4.45,
        4.36]),
 array([4.76, 4.69, 4.58, 4.42, 4.3 , 4.13, 4.1 , 4.05, 4.1 , 4.18, 4.45,
        4.36]),
 array([4.76, 4.69, 4.58, 4.42, 4.3 , 4.13, 4.1 , 4.05, 4.1 , 4.18, 4.45,
        4.36]),
 array([4.76, 4.69, 4.58, 4.42, 4.3 , 4.13, 4.1 , 4.05, 4.1 , 4.18, 4.45,
        4.36]),
 array([4.76, 4.69, 4.58, 4.42, 4.3 , 4.13, 4.1 , 4.05, 4.1 , 4.18, 4.45,
        4.36])]

In [ ]:
for h in range(0, 5):
    if h == 0:
        target_col = ori_col
    else:
        target_col = [f'{element}_+_{h}' for element in ori_col]
    
    feature_col = [element for element in all_cols if 'window' in element]

    df_train_modified = df_train[:(len_train-h)]
    df_test_modified = df_test.iloc[[0]]
    print(len(df_train_modified))

    X_train, y_train = df_train_modified[feature_col], df_train_modified[target_col]
    X_test, y_test = df_test_modified[feature_col], df_test.iloc[h][ori_col]

X_test