In [4]:
import pickle
import numpy as np 
import pandas as pd 
import math

import sys
sys.path.append('../utils')
from treasury_base import *
from scipy.stats import t
from sklearn.metrics import mean_squared_error as mse

In [6]:
with open("pickle/dfs_5_steps_ahead.pkl", "rb") as file:
    loaded_dataframes = pickle.load(file)

# Extract individual DataFrames
naive_df = loaded_dataframes["naive_df"]
kan_df = loaded_dataframes["kan_df"]
truth_df = loaded_dataframes["truth_df"]

# Use the DataFrames
truth_df

1 Mo  2 Mo  3 Mo  6 Mo  1 Yr  2 Yr  3 Yr  5 Yr  7 Yr  10 Yr  \
Date                                                                      
2024-11-07  4.69  4.69  4.63  4.40  4.28  4.21  4.13  4.17  4.25   4.31   
2024-11-08  4.70  4.69  4.63  4.42  4.32  4.26  4.18  4.20  4.25   4.30   
2024-11-12  4.70  4.70  4.63  4.45  4.38  4.34  4.29  4.32  4.38   4.43   
2024-11-13  4.69  4.67  4.60  4.40  4.31  4.27  4.25  4.30  4.38   4.44   
2024-11-14  4.70  4.68  4.61  4.43  4.36  4.34  4.30  4.32  4.38   4.43   
2024-11-15  4.70  4.67  4.60  4.44  4.34  4.31  4.27  4.30  4.36   4.43   
2024-11-18  4.70  4.65  4.63  4.44  4.33  4.29  4.25  4.28  4.35   4.42   
2024-11-19  4.67  4.63  4.62  4.44  4.34  4.27  4.24  4.25  4.32   4.39   
2024-11-20  4.68  4.63  4.62  4.44  4.37  4.31  4.26  4.28  4.34   4.41   
2024-11-21  4.72  4.67  4.63  4.45  4.39  4.34  4.30  4.30  4.36   4.43   
2024-11-22  4.72  4.67  4.63  4.46  4.42  4.37  4.32  4.30  4.35   4.41   
2024-11-25  4.74  4.67  4.62  4.46  4.37  4.21  4.21  4.17  4.21   4.27   
2024-11-26  4.74  4.67  4.61  4.45  4.37  4.21  4.21  4.17  4.24   4.30   
2024-11-27  4.76  4.70  4.60  4.43  4.34  4.19  4.17  4.11  4.17   4.25   
2024-11-29  4.76  4.69  4.58  4.42  4.30  4.13  4.10  4.05  4.10   4.18   
2024-12-02  4.75  4.63  4.51  4.43  4.30  4.17  4.11  4.08  4.13   4.19   
2024-12-03  4.66  4.56  4.49  4.40  4.27  4.17  4.13  4.11  4.17   4.23   
2024-12-04  4.65  4.54  4.47  4.38  4.23  4.13  4.09  4.07  4.13   4.19   
2024-12-05  4.59  4.53  4.46  4.38  4.23  4.15  4.10  4.07  4.12   4.17   
2024-12-06  4.57  4.50  4.42  4.34  4.19  4.10  4.05  4.03  4.09   4.15   

            20 Yr  30 Yr  
Date                      
2024-11-07   4.62   4.52  
2024-11-08   4.58   4.47  
2024-11-12   4.70   4.58  
2024-11-13   4.73   4.63  
2024-11-14   4.69   4.58  
2024-11-15   4.70   4.60  
2024-11-18   4.70   4.61  
2024-11-19   4.66   4.57  
2024-11-20   4.66   4.59  
2024-11-21   4.68   4.61  
2024-11-22   4.67   4.60  
2024-11-25   4.53   4.45  
2024-11-26   4.56   4.48  
2024-11-27   4.52   4.44  
2024-11-29   4.45   4.36  
2024-12-02   4.46   4.36  
2024-12-03   4.50   4.40  
2024-12-04   4.45   4.35  
2024-12-05   4.43   4.33  
2024-12-06   4.42   4.34

In [8]:
cols = truth_value.columns

for i in range(12):
    y1 = kan_df.iloc[:, i].values
    y2 = naive_df.iloc[:, i].values
    y = truth_value.iloc[:, i].values

    test = DM(y1,y2,y,h=4)
    

    print(f'{cols[i]}: {t.cdf(test, df=19)}')

1 Mo: 0.20288591049950933
2 Mo: 0.8656533831977438
3 Mo: 0.6197245375207994
6 Mo: 0.9997547732184617
1 Yr: 0.7885771765847889
2 Yr: 0.027119533499680548
3 Yr: 0.0467393024217196
5 Yr: 0.0008928372441414762
7 Yr: 7.462234038345484e-06
10 Yr: 0.012336208132617177
20 Yr: 0.003767996708989954
30 Yr: 0.004025432916249031


In [9]:
y1

array([4.41495509, 4.41236799, 4.41186676, 4.41167705, 4.41391378,
       4.55343734, 4.54219394, 4.52894181, 4.51791132, 4.50797545,
       4.54099105, 4.52420293, 4.50677568, 4.4848    , 4.46877979,
       4.52827669, 4.50571238, 4.48394303, 4.46383583, 4.44346956])

In [10]:
y2

array([4.6 , 4.6 , 4.6 , 4.6 , 4.6 , 4.58, 4.58, 4.58, 4.58, 4.58, 4.61,
       4.61, 4.61, 4.61, 4.61, 4.36, 4.36, 4.36, 4.36, 4.36])

In [11]:
y

array([4.34, 4.36, 4.61, 4.58, 4.34, 4.36, 4.61, 4.58, 4.34, 4.36, 4.61,
       4.58, 4.34, 4.36, 4.61, 4.58, 4.34, 4.36, 4.61, 4.58])

In [14]:
mse(y1, y)

np.float64(0.016814762542915244)